
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
let chromium;try{({chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'))}catch{}
const base=process.env.LANGUAGE_TEST_URL,opts={skip:!chromium||!base,timeout:60000};
const source=fs.readFileSync(__dirname+'/dynamic-language.test.cjs','utf8');
const fixture=new Function(source.slice(source.indexOf('const names ='),source.indexOf('async function open'))+';return fixture;')();
async function setup(browser,path){const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{const q=r.request(),u=q.url();if(['fetch','xhr'].includes(q.resourceType())&&!u.includes('/src/')&&!u.includes('/node_modules/'))return r.fulfill({json:{status:true,data:fixture(u,'en')}});return u.startsWith(base)?r.continue():r.abort()});await p.goto(base+path);return {p,errors}}
test('fresh mobile tabs open the requested route and browser back restores it',opts,async()=>{const b=await chromium.launch();try{const {p,errors}=await setup(b,'/store');await p.waitForSelector('iframe');assert.equal(new URL(await p.locator('iframe').getAttribute('src'),base).searchParams.get('view'),'store');const frame=p.frameLocator('iframe');await frame.locator('[data-tab="home"]').click();await p.waitForURL(base+'/');await p.goBack();await p.waitForURL(base+'/store');await p.waitForTimeout(400);assert.equal(new URL(await p.locator('iframe').getAttribute('src'),base).searchParams.get('view'),'store');assert.deepEqual(errors,[]);const detail=await setup(b,'/services/3');await detail.p.frameLocator('iframe').locator('.mobile-sd').waitFor();assert.deepEqual(detail.errors,[])}finally{await b.close()}});
for(const file of ['index.html','index.dynamic.html'])test('booking summary opens at bottom and preserves selected services: '+file,opts,async()=>{const b=await chromium.launch();try{const {p,errors}=await setup(b,'/mobile/'+file+'?view=booking');await p.locator('[data-booking-launch-branch]').first().click();assert.equal(await p.locator('#bookingServiceOverlay').count(),0);assert.equal(await p.locator('.booking-service-sheet').count(),0);const card=await p.locator('[data-w-cat]').first().boundingBox();assert.ok(card.width>=100&&card.height>=130);assert.notEqual(await p.locator('body').evaluate(e=>getComputedStyle(e).overflowY),'hidden');await p.locator('[data-w-cat]').first().click();await p.locator('[data-w-svc]').first().click();assert.equal(await p.locator('.booking-stage .booking-service-summary').count(),0);await p.locator('[data-booking-summary]').first().click();const dialog=p.locator('#bookingSummarySheet');await dialog.waitFor({state:'visible'});assert.equal(await dialog.locator('.service-summary-items .service-summary-item').count(),1);assert.equal(await dialog.evaluate(e=>getComputedStyle(e).animationName),'summarySlideIn');await p.waitForTimeout(450);const box=await dialog.boundingBox();assert.ok(Math.abs(box.y+box.height-844)<2);await p.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await dialog.evaluate(e=>e.open),false);assert.equal(await p.locator('[data-w-svc].sel').count(),1);await p.locator('#wizPrevBtn').click();await p.locator('[data-booking-launch-branch]').first().waitFor({state:'visible'});assert.deepEqual(errors,[])}finally{await b.close()}});
