<?php

return [
    '/' => ['label' => 'الرئيسية', 'ar' => ['title' => 'الرئيسية | عناية سامي', 'keywords' => '', 'description' => 'خدمات العناية الرجالية والحلاقة والمساج والباقات في جدة. احجز تجربتك مع عناية سامي.'], 'en' => ['title' => 'Home | Sami Care', 'keywords' => '', 'description' => 'Men’s grooming, haircuts, massages and packages in Jeddah. Book your experience with Sami Care.']],
    '/services' => ['label' => 'الخدمات', 'ar' => ['title' => 'الخدمات | عناية سامي', 'keywords' => '', 'description' => 'اكتشف خدمات عناية سامي واختر الخدمة والموعد المناسبين لك.'], 'en' => ['title' => 'Services | Sami Care', 'keywords' => '', 'description' => 'Explore Sami Care services and choose your preferred service and appointment.']],
    '/store' => ['label' => 'المنتجات', 'ar' => ['title' => 'المنتجات | عناية سامي', 'keywords' => '', 'description' => 'تصفح منتجات العناية بالشعر والبشرة واللحية من عناية سامي.'], 'en' => ['title' => 'Products | Sami Care', 'keywords' => '', 'description' => 'Browse hair, skin and beard care products from Sami Care.']],
    '/gifts' => ['label' => 'الإهداء', 'ar' => ['title' => 'الإهداء | عناية سامي', 'keywords' => '', 'description' => 'أهدِ من تحب تجربة عناية مميزة مع بطاقات وهدايا عناية سامي.'], 'en' => ['title' => 'Gifts | Sami Care', 'keywords' => '', 'description' => 'Give someone you love a special care experience with Sami Care gifts.']],
    '/packages-gifts' => ['label' => 'الباقات', 'ar' => ['title' => 'الباقات | عناية سامي', 'keywords' => '', 'description' => 'اكتشف باقات عناية سامي واحجز مجموعة الخدمات المناسبة لك.'], 'en' => ['title' => 'Packages | Sami Care', 'keywords' => '', 'description' => 'Explore Sami Care packages and book the services that suit you.']],
    '/branches' => ['label' => 'الفروع', 'ar' => ['title' => 'الفروع | عناية سامي', 'keywords' => '', 'description' => 'تعرف على فروع عناية سامي ومواقعها وطرق التواصل معها.'], 'en' => ['title' => 'Branches | Sami Care', 'keywords' => '', 'description' => 'Find Sami Care branches, locations and contact information.']],
    '/contact' => ['label' => 'تواصل معنا', 'ar' => ['title' => 'تواصل معنا | عناية سامي', 'keywords' => '', 'description' => 'تواصل مع فريق عناية سامي للاستفسارات والمساعدة.'], 'en' => ['title' => 'Contact us | Sami Care', 'keywords' => '', 'description' => 'Contact the Sami Care team for enquiries and assistance.']],
    '/page-about' => ['label' => 'عن عناية سامي', 'ar' => ['title' => 'عن عناية سامي | عناية سامي', 'keywords' => '', 'description' => 'تعرف على مركز عناية سامي وخدماته وفروعه في جدة.'], 'en' => ['title' => 'About Sami Care | Sami Care', 'keywords' => '', 'description' => 'Learn about Sami Care, our services and our branches in Jeddah.']],
    '/blog' => ['label' => 'المدونة', 'ar' => ['title' => 'المدونة | عناية سامي', 'keywords' => '', 'description' => 'اقرأ مقالات ونصائح العناية الرجالية من عناية سامي.'], 'en' => ['title' => 'Blog | Sami Care', 'keywords' => '', 'description' => 'Read men’s grooming articles and care tips from Sami Care.']],
    '/home-service' => ['label' => 'الخدمة المنزلية', 'ar' => ['title' => 'الخدمة المنزلية | عناية سامي', 'keywords' => '', 'description' => 'احجز خدمات عناية سامي المنزلية في جدة.'], 'en' => ['title' => 'Home service | Sami Care', 'keywords' => '', 'description' => 'Book Sami Care home services in Jeddah.']],
    '/cafe' => ['label' => 'المقهى', 'ar' => ['title' => 'المقهى | عناية سامي', 'keywords' => '', 'description' => 'تعرف على مقهى عناية سامي واستمتع باستراحتك.'], 'en' => ['title' => 'Cafe | Sami Care', 'keywords' => '', 'description' => 'Discover the Sami Care cafe and enjoy your break.']],
    '/booking' => ['label' => 'الحجز', 'ar' => ['title' => 'الحجز | عناية سامي', 'keywords' => '', 'description' => 'اختر خدماتك وموعدك وأكمل حجزك لدى عناية سامي.'], 'en' => ['title' => 'Booking | Sami Care', 'keywords' => '', 'description' => 'Choose your services and appointment and complete your Sami Care booking.']],
    '/booking-receipt' => ['label' => 'إيصال الحجز', 'ar' => ['title' => 'إيصال الحجز | عناية سامي', 'keywords' => '', 'description' => 'تفاصيل وإيصال حجزك لدى عناية سامي.'], 'en' => ['title' => 'Booking receipt | Sami Care', 'keywords' => '', 'description' => 'Your Sami Care booking details and receipt.']],
    '/gift-recipient' => ['label' => 'استلام الهدية', 'ar' => ['title' => 'استلام الهدية | عناية سامي', 'keywords' => '', 'description' => 'اطلع على هديتك من عناية سامي وتفاصيل استخدامها.'], 'en' => ['title' => 'Receive your gift | Sami Care', 'keywords' => '', 'description' => 'View your Sami Care gift and how to use it.']],
    '/account' => ['label' => 'حسابي', 'ar' => ['title' => 'حسابي | عناية سامي', 'keywords' => '', 'description' => 'إدارة حسابك وحجوزاتك وطلباتك لدى عناية سامي.'], 'en' => ['title' => 'My account | Sami Care', 'keywords' => '', 'description' => 'Manage your Sami Care account, bookings and orders.']],
    '/terms' => ['label' => 'الشروط والأحكام', 'ar' => ['title' => 'الشروط والأحكام | عناية سامي', 'keywords' => '', 'description' => 'اطلع على شروط وأحكام استخدام خدمات عناية سامي.'], 'en' => ['title' => 'Terms and conditions | Sami Care', 'keywords' => '', 'description' => 'Read the terms and conditions for Sami Care services.']],
    '/privacy-policy' => ['label' => 'سياسة الخصوصية', 'ar' => ['title' => 'سياسة الخصوصية | عناية سامي', 'keywords' => '', 'description' => 'تعرف على سياسة الخصوصية وحماية البيانات لدى عناية سامي.'], 'en' => ['title' => 'Privacy policy | Sami Care', 'keywords' => '', 'description' => 'Read how Sami Care handles privacy and protects your data.']],
];
